trigger:
- main

pool:
  name: Default

variables:
  IMAGE_NAME: sample-project
  PROJECT_ID: lyrical-chassis-459113-c9
  GCR_REGION: asia-south1
  CLUSTER_NAME: demo-gke
  CLUSTER_REGION: asia-south1
  GKE_NAMESPACE: jhapcore
  DEPLOYMENT_NAME: sample-app

steps:
- checkout: self

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    options: '-DskipTests'
  displayName: 'Build with Maven'

- script: |
    docker build -t $GCR_REGION-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:$(Build.BuildId) .
    docker push $GCR_REGION-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:$(Build.BuildId)
  displayName: 'Docker Build & Push to GCR'

- script: |
    gcloud container clusters get-credentials $CLUSTER_NAME --region $CLUSTER_REGION --project $PROJECT_ID
    kubectl set image deployment/$DEPLOYMENT_NAME $DEPLOYMENT_NAME=$GCR_REGION-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:$(Build.BuildId) -n $GKE_NAMESPACE
  displayName: 'Deploy to GKE'
