resources:
- repo: self
  fetchDepth: 1

variables:
  BuildConfiguration: 'Release'
  DockerRegistry: "lyrical-chassis-459113-c9/sample-project"
  ImageName: "sample-project"

trigger:
- main

stages:
- stage: Testbuild
  pool:
    name: Default
  jobs:
  - job: Build
    steps:
    - checkout: self
    - script: |
        ./gradlew clean build -x test
      displayName: 'Build Package'
        
    - task: Docker@2
      displayName: 'Docker Login to GCP'
      inputs:
        containerRegistry: 'gcp-demo'
        command: 'login'

    - task: Docker@2
      displayName: 'Docker Build and Push'
      inputs:
        repository: '$(DockerRegistry)/$(ImageName)'
        command: 'buildAndPush'
        Dockerfile: './Dockerfile'
        tags: 2.0.0


- stage: Deploy
  pool: 
    name: Default
  jobs: 
  - job: Restart_Pod
    steps: 
    - script: |
        kubectl rollout restart deployment sample-app -n jhapcore
      displayName: "Restart Kubernets Deployment"
